### ISSUE TITLE
Failure to run

### ISSUE THREAD

**Issue by L1lith** [socketkit/awacs#11]
I was trying to figure out how to run this project, and I'm getting an error. Here are the commands I ran
```bash
git clone https://github.com/socketkit/awacs
npm install
npm run dev
```
The first two commands run fine but when I try to run the project in dev mode this happens
![error message](https://user-images.githubusercontent.com/34887287/127465804-594ae0f6-7c02-4c9b-808e-efdce26437ef.PNG)

**Comment by anonrig** [comment]
Hi @L1lith 

Thank you for your feedback. Unfortunately, you didn't include the necessary configuration for the PostgreSQL configuration. If you're using Awacs locally, you should include the necessary config for PostgreSQL connection. Please use the following documentation to change the environment variables that suits for your needs. https://awacs.socketkit.com/getting-started/configuration.

Have a great day!
Yagiz
